
// This file has been generated by the GUI designer. Do not modify.
namespace InterfataSimOutorder
{
	public partial class SecondaryWindow
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lbResult;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget InterfataSimOutorder.SecondaryWindow
			this.Name = "InterfataSimOutorder.SecondaryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Results for Client number #");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child InterfataSimOutorder.SecondaryWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbResult = new global::Gtk.Label();
			this.lbResult.Name = "lbResult";
			this.lbResult.LabelProp = global::Mono.Unix.Catalog.GetString("LABEL");
			this.fixed1.Add(this.lbResult);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbResult]));
			w1.X = 29;
			w1.Y = 22;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
