
// This file has been generated by the GUI designer. Do not modify.
namespace InterfataSimOutorder
{
	public partial class SecondaryWindow
	{
		private global::Gtk.Fixed fixed1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget InterfataSimOutorder.SecondaryWindow
			this.Name = "InterfataSimOutorder.SecondaryWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Results for Client number #");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child InterfataSimOutorder.SecondaryWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HasWindow = false;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
