
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label2;

	private global::Gtk.SpinButton spinInstrNum;

	private global::Gtk.SpinButton spinFastForwardCount;

	private global::Gtk.Label label3;

	private global::Gtk.Button btnStartServer;

	private global::Gtk.Button btnReset;

	private global::Gtk.Button btnHelp;

	private global::Gtk.CheckButton chkFetch;

	private global::Gtk.Label lbFetchOption;

	private global::Gtk.ComboBox comboFetchOption;

	private global::Gtk.Label lbFetchValue;

	private global::Gtk.SpinButton spinFetch;

	private global::Gtk.CheckButton chkBpred;

	private global::Gtk.Label lbBpred;

	private global::Gtk.ComboBox comboBpred;

	private global::Gtk.Label lbBpred2levL1Size;

	private global::Gtk.SpinButton spinBpred2levL1Size;

	private global::Gtk.SpinButton spinBpred2levL2Size;

	private global::Gtk.Label lbBpred2levL2Size;

	private global::Gtk.SpinButton spinBpredRasRasSize;

	private global::Gtk.Label lbBpredRasRasSize;

	private global::Gtk.Label lbBpredCombMetaTableSize;

	private global::Gtk.SpinButton spinBpredCombMetaTableSize;

	private global::Gtk.SpinButton spinBpredBtbNumSets;

	private global::Gtk.Label lbBpredBtbNumSets;

	private global::Gtk.SpinButton spinBpredBtbAssociativity;

	private global::Gtk.SpinButton spinBpred2levHistSize;

	private global::Gtk.SpinButton spinBpredBimodTableSize;

	private global::Gtk.Label lbBpred2levHistSize;

	private global::Gtk.Label lbBpredBimodTableSize;

	private global::Gtk.Label lbBpredBtbAssociativity;

	private global::Gtk.Label lbBpredSpecUpdate;

	private global::Gtk.ComboBox comboBpredSpecUpdate;

	private global::Gtk.CheckButton chkDecode;

	private global::Gtk.SpinButton spinDecodeWidth;

	private global::Gtk.Label lbDecodeWidth;

	private global::Gtk.SpinButton spinCommitWidth;

	private global::Gtk.CheckButton chkCommit;

	private global::Gtk.CheckButton chkIssue;

	private global::Gtk.Label lbIssue;

	private global::Gtk.ComboBox comboIssue;

	private global::Gtk.Label lbIssueWidth;

	private global::Gtk.SpinButton spinIssueWidth;

	private global::Gtk.ComboBox comboIssueInorder;

	private global::Gtk.Label lbIssueInorder;

	private global::Gtk.Label lbCommitWidth;

	private global::Gtk.Label lbIssueWrongPath;

	private global::Gtk.ComboBox comboIssueWrongPath;

	private global::Gtk.CheckButton chkRuu;

	private global::Gtk.SpinButton spinRuuSize;

	private global::Gtk.CheckButton chkLsq;

	private global::Gtk.Label lbRuuSize;

	private global::Gtk.SpinButton spinLsqSize;

	private global::Gtk.Label lbLsqSize;

	private global::Gtk.CheckButton chkDL1;

	private global::Gtk.Label lbNumSetsDL1;

	private global::Gtk.SpinButton spinNumSetsDL1;

	private global::Gtk.SpinButton spinBlockSizeDL1;

	private global::Gtk.SpinButton spinAssociativityDL1;

	private global::Gtk.ComboBox comboReplacementDL1;

	private global::Gtk.CheckButton chkDL2;

	private global::Gtk.SpinButton spinAssociativityDL2;

	private global::Gtk.SpinButton spinLatDL2;

	private global::Gtk.SpinButton spinBlockSizeDL2;

	private global::Gtk.SpinButton spinNumSetsDL2;

	private global::Gtk.ComboBox comboReplacementDL2;

	private global::Gtk.Label lbLatDL2;

	private global::Gtk.Label lbReplacementDL2;

	private global::Gtk.Label lbAssociativityDL2;

	private global::Gtk.Label lbBlockSizeDL2;

	private global::Gtk.Label lbNumSetsDL2;

	private global::Gtk.SpinButton spinLatDL1;

	private global::Gtk.Label lbLatDL1;

	private global::Gtk.Label lbReplacementDL1;

	private global::Gtk.Label lbAssociativityDL1;

	private global::Gtk.Label lbBlockSizeDL1;

	private global::Gtk.CheckButton chkIL1;

	private global::Gtk.SpinButton spinNumSetsIL1;

	private global::Gtk.SpinButton spinBlockSizeIL1;

	private global::Gtk.SpinButton spinAssociativityIL1;

	private global::Gtk.ComboBox comboReplacementIL1;

	private global::Gtk.SpinButton spinLatIL1;

	private global::Gtk.Label lbNumSetsIL1;

	private global::Gtk.Label lbBlockSizeIL1;

	private global::Gtk.Label lbAssociativityIL1;

	private global::Gtk.Label lbReplacementIL1;

	private global::Gtk.Label lbLatIL1;

	private global::Gtk.CheckButton chkUnifiedIL1;

	private global::Gtk.CheckButton chkIL2;

	private global::Gtk.SpinButton spinNumSetsIL2;

	private global::Gtk.SpinButton spinBlockSizeIL2;

	private global::Gtk.SpinButton spinAssociativityIL2;

	private global::Gtk.ComboBox comboReplacementIL2;

	private global::Gtk.SpinButton spinLatIL2;

	private global::Gtk.CheckButton chkUnifiedIL2;

	private global::Gtk.Label lbNumSetsIL2;

	private global::Gtk.Label lbBlockSizeIL2;

	private global::Gtk.Label lbAssociativityIL2;

	private global::Gtk.Label lbReplacementIL2;

	private global::Gtk.Label lbLatIL2;

	private global::Gtk.Label lbNumSetsDTLB;

	private global::Gtk.CheckButton chkDTLB;

	private global::Gtk.SpinButton spinNumSetsDTLB;

	private global::Gtk.SpinButton spinBlockSizeDTLB;

	private global::Gtk.Label lbBlockSizeDTLB;

	private global::Gtk.SpinButton spinAssociativityDTLB;

	private global::Gtk.Label lbAssociativityDTLB;

	private global::Gtk.ComboBox comboReplacementDTLB;

	private global::Gtk.Label lbReplacementDTLB;

	private global::Gtk.Label lbLatTLB;

	private global::Gtk.SpinButton spinLatTLB;

	private global::Gtk.CheckButton chkITLB;

	private global::Gtk.Label lbNumSetsITLB;

	private global::Gtk.SpinButton spinNumSetsITLB;

	private global::Gtk.SpinButton spinBlockSizeITLB;

	private global::Gtk.SpinButton spinAssociativityITLB;

	private global::Gtk.ComboBox comboReplacementITLB;

	private global::Gtk.Label lbBlockSizeITLB;

	private global::Gtk.Label lbAssociativityITLB;

	private global::Gtk.Label lbReplacementITLB;

	private global::Gtk.ComboBox comboCacheFlush;

	private global::Gtk.ComboBox comboCacheIcompress;

	private global::Gtk.SpinButton spinMemWidth;

	private global::Gtk.CheckButton chkCacheFlush;

	private global::Gtk.CheckButton chkCacheIcompress;

	private global::Gtk.CheckButton chkMemWidth;

	private global::Gtk.CheckButton chkMemLat;

	private global::Gtk.Label lbMemLatInterChunk;

	private global::Gtk.Label lbMemLatFirstChunk;

	private global::Gtk.SpinButton spinMemLatInterChunk;

	private global::Gtk.SpinButton spinMemLatFirstChunk;

	private global::Gtk.Button btnPopulate;

	private global::Gtk.Button btnSeeResults;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Server");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Number of instructions:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w1.X = 18;
		w1.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinInstrNum = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinInstrNum.CanFocus = true;
		this.spinInstrNum.Name = "spinInstrNum";
		this.spinInstrNum.Adjustment.PageIncrement = 10D;
		this.spinInstrNum.Adjustment.PageSize = 100000D;
		this.spinInstrNum.ClimbRate = 1D;
		this.spinInstrNum.Numeric = true;
		this.spinInstrNum.Value = 10000D;
		this.fixed1.Add(this.spinInstrNum);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinInstrNum]));
		w2.X = 166;
		w2.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinFastForwardCount = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinFastForwardCount.CanFocus = true;
		this.spinFastForwardCount.Name = "spinFastForwardCount";
		this.spinFastForwardCount.Adjustment.PageIncrement = 10D;
		this.spinFastForwardCount.Adjustment.PageSize = 100000D;
		this.spinFastForwardCount.ClimbRate = 1D;
		this.spinFastForwardCount.Numeric = true;
		this.fixed1.Add(this.spinFastForwardCount);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinFastForwardCount]));
		w3.X = 166;
		w3.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Fast Forward:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w4.X = 74;
		w4.Y = 56;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnStartServer = new global::Gtk.Button();
		this.btnStartServer.Sensitive = false;
		this.btnStartServer.CanFocus = true;
		this.btnStartServer.Name = "btnStartServer";
		this.btnStartServer.UseUnderline = true;
		this.btnStartServer.Label = global::Mono.Unix.Catalog.GetString("Start Server");
		this.fixed1.Add(this.btnStartServer);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnStartServer]));
		w5.X = 310;
		w5.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnReset = new global::Gtk.Button();
		this.btnReset.CanFocus = true;
		this.btnReset.Name = "btnReset";
		this.btnReset.UseUnderline = true;
		this.btnReset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.fixed1.Add(this.btnReset);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnReset]));
		w6.X = 395;
		w6.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnHelp = new global::Gtk.Button();
		this.btnHelp.CanFocus = true;
		this.btnHelp.Name = "btnHelp";
		this.btnHelp.UseUnderline = true;
		this.btnHelp.Label = global::Mono.Unix.Catalog.GetString("Help");
		this.fixed1.Add(this.btnHelp);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnHelp]));
		w7.X = 399;
		w7.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkFetch = new global::Gtk.CheckButton();
		this.chkFetch.CanFocus = true;
		this.chkFetch.Name = "chkFetch";
		this.chkFetch.Label = global::Mono.Unix.Catalog.GetString("with fetch");
		this.chkFetch.DrawIndicator = true;
		this.chkFetch.UseUnderline = true;
		this.fixed1.Add(this.chkFetch);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkFetch]));
		w8.X = 23;
		w8.Y = 94;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbFetchOption = new global::Gtk.Label();
		this.lbFetchOption.Name = "lbFetchOption";
		this.lbFetchOption.LabelProp = global::Mono.Unix.Catalog.GetString("Fetch Option:");
		this.fixed1.Add(this.lbFetchOption);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbFetchOption]));
		w9.X = 24;
		w9.Y = 121;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboFetchOption = global::Gtk.ComboBox.NewText();
		this.comboFetchOption.AppendText(global::Mono.Unix.Catalog.GetString("ifqsize"));
		this.comboFetchOption.AppendText(global::Mono.Unix.Catalog.GetString("mplat"));
		this.comboFetchOption.AppendText(global::Mono.Unix.Catalog.GetString("speed"));
		this.comboFetchOption.Name = "comboFetchOption";
		this.comboFetchOption.Active = 0;
		this.fixed1.Add(this.comboFetchOption);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboFetchOption]));
		w10.X = 116;
		w10.Y = 113;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbFetchValue = new global::Gtk.Label();
		this.lbFetchValue.Name = "lbFetchValue";
		this.lbFetchValue.LabelProp = global::Mono.Unix.Catalog.GetString("Fetch Value:");
		this.fixed1.Add(this.lbFetchValue);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbFetchValue]));
		w11.X = 25;
		w11.Y = 150;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinFetch = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinFetch.CanFocus = true;
		this.spinFetch.Name = "spinFetch";
		this.spinFetch.Adjustment.PageIncrement = 10D;
		this.spinFetch.Adjustment.PageSize = 100000D;
		this.spinFetch.ClimbRate = 1D;
		this.spinFetch.Numeric = true;
		this.spinFetch.Value = 4D;
		this.fixed1.Add(this.spinFetch);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinFetch]));
		w12.X = 102;
		w12.Y = 149;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkBpred = new global::Gtk.CheckButton();
		this.chkBpred.CanFocus = true;
		this.chkBpred.Name = "chkBpred";
		this.chkBpred.Label = global::Mono.Unix.Catalog.GetString("with bpred options");
		this.chkBpred.Active = true;
		this.chkBpred.DrawIndicator = true;
		this.chkBpred.UseUnderline = true;
		this.fixed1.Add(this.chkBpred);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkBpred]));
		w13.X = 21;
		w13.Y = 181;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpred = new global::Gtk.Label();
		this.lbBpred.Name = "lbBpred";
		this.lbBpred.LabelProp = global::Mono.Unix.Catalog.GetString("Bpred option:");
		this.fixed1.Add(this.lbBpred);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpred]));
		w14.X = 21;
		w14.Y = 212;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboBpred = global::Gtk.ComboBox.NewText();
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("bimod"));
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("2lev"));
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("comb"));
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("ras"));
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("btb"));
		this.comboBpred.AppendText(global::Mono.Unix.Catalog.GetString("spec_update"));
		this.comboBpred.Name = "comboBpred";
		this.comboBpred.Active = 0;
		this.fixed1.Add(this.comboBpred);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboBpred]));
		w15.X = 107;
		w15.Y = 205;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpred2levL1Size = new global::Gtk.Label();
		this.lbBpred2levL1Size.Name = "lbBpred2levL1Size";
		this.lbBpred2levL1Size.LabelProp = global::Mono.Unix.Catalog.GetString("Cache L1 Size:");
		this.fixed1.Add(this.lbBpred2levL1Size);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpred2levL1Size]));
		w16.X = 21;
		w16.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpred2levL1Size = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpred2levL1Size.CanFocus = true;
		this.spinBpred2levL1Size.Name = "spinBpred2levL1Size";
		this.spinBpred2levL1Size.Adjustment.PageIncrement = 10D;
		this.spinBpred2levL1Size.Adjustment.PageSize = 100000D;
		this.spinBpred2levL1Size.ClimbRate = 1D;
		this.spinBpred2levL1Size.Numeric = true;
		this.spinBpred2levL1Size.Value = 1D;
		this.fixed1.Add(this.spinBpred2levL1Size);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpred2levL1Size]));
		w17.X = 107;
		w17.Y = 241;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpred2levL2Size = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpred2levL2Size.CanFocus = true;
		this.spinBpred2levL2Size.Name = "spinBpred2levL2Size";
		this.spinBpred2levL2Size.Adjustment.PageIncrement = 10D;
		this.spinBpred2levL2Size.Adjustment.PageSize = 100000D;
		this.spinBpred2levL2Size.ClimbRate = 1D;
		this.spinBpred2levL2Size.Numeric = true;
		this.spinBpred2levL2Size.Value = 1024D;
		this.fixed1.Add(this.spinBpred2levL2Size);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpred2levL2Size]));
		w18.X = 105;
		w18.Y = 272;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpred2levL2Size = new global::Gtk.Label();
		this.lbBpred2levL2Size.Name = "lbBpred2levL2Size";
		this.lbBpred2levL2Size.LabelProp = global::Mono.Unix.Catalog.GetString("Cache L2 Size:");
		this.fixed1.Add(this.lbBpred2levL2Size);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpred2levL2Size]));
		w19.X = 19;
		w19.Y = 274;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpredRasRasSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpredRasRasSize.CanFocus = true;
		this.spinBpredRasRasSize.Name = "spinBpredRasRasSize";
		this.spinBpredRasRasSize.Adjustment.PageIncrement = 10D;
		this.spinBpredRasRasSize.Adjustment.PageSize = 100000D;
		this.spinBpredRasRasSize.ClimbRate = 1D;
		this.spinBpredRasRasSize.Numeric = true;
		this.spinBpredRasRasSize.Value = 8D;
		this.fixed1.Add(this.spinBpredRasRasSize);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpredRasRasSize]));
		w20.X = 104;
		w20.Y = 303;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredRasRasSize = new global::Gtk.Label();
		this.lbBpredRasRasSize.Name = "lbBpredRasRasSize";
		this.lbBpredRasRasSize.LabelProp = global::Mono.Unix.Catalog.GetString("Ras Size:");
		this.fixed1.Add(this.lbBpredRasRasSize);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredRasRasSize]));
		w21.X = 48;
		w21.Y = 305;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredCombMetaTableSize = new global::Gtk.Label();
		this.lbBpredCombMetaTableSize.Name = "lbBpredCombMetaTableSize";
		this.lbBpredCombMetaTableSize.LabelProp = global::Mono.Unix.Catalog.GetString("Meta Table Size:");
		this.fixed1.Add(this.lbBpredCombMetaTableSize);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredCombMetaTableSize]));
		w22.X = 207;
		w22.Y = 306;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpredCombMetaTableSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpredCombMetaTableSize.CanFocus = true;
		this.spinBpredCombMetaTableSize.Name = "spinBpredCombMetaTableSize";
		this.spinBpredCombMetaTableSize.Adjustment.PageIncrement = 10D;
		this.spinBpredCombMetaTableSize.Adjustment.PageSize = 100000D;
		this.spinBpredCombMetaTableSize.ClimbRate = 1D;
		this.spinBpredCombMetaTableSize.Numeric = true;
		this.spinBpredCombMetaTableSize.Value = 1024D;
		this.fixed1.Add(this.spinBpredCombMetaTableSize);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpredCombMetaTableSize]));
		w23.X = 302;
		w23.Y = 301;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpredBtbNumSets = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpredBtbNumSets.CanFocus = true;
		this.spinBpredBtbNumSets.Name = "spinBpredBtbNumSets";
		this.spinBpredBtbNumSets.Adjustment.PageIncrement = 10D;
		this.spinBpredBtbNumSets.Adjustment.PageSize = 100000D;
		this.spinBpredBtbNumSets.ClimbRate = 1D;
		this.spinBpredBtbNumSets.Numeric = true;
		this.spinBpredBtbNumSets.Value = 512D;
		this.fixed1.Add(this.spinBpredBtbNumSets);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpredBtbNumSets]));
		w24.X = 104;
		w24.Y = 335;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredBtbNumSets = new global::Gtk.Label();
		this.lbBpredBtbNumSets.Name = "lbBpredBtbNumSets";
		this.lbBpredBtbNumSets.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbBpredBtbNumSets);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredBtbNumSets]));
		w25.X = 7;
		w25.Y = 339;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpredBtbAssociativity = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpredBtbAssociativity.CanFocus = true;
		this.spinBpredBtbAssociativity.Name = "spinBpredBtbAssociativity";
		this.spinBpredBtbAssociativity.Adjustment.PageIncrement = 10D;
		this.spinBpredBtbAssociativity.Adjustment.PageSize = 100000D;
		this.spinBpredBtbAssociativity.ClimbRate = 1D;
		this.spinBpredBtbAssociativity.Numeric = true;
		this.spinBpredBtbAssociativity.Value = 4D;
		this.fixed1.Add(this.spinBpredBtbAssociativity);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpredBtbAssociativity]));
		w26.X = 302;
		w26.Y = 333;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpred2levHistSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpred2levHistSize.CanFocus = true;
		this.spinBpred2levHistSize.Name = "spinBpred2levHistSize";
		this.spinBpred2levHistSize.Adjustment.PageIncrement = 10D;
		this.spinBpred2levHistSize.Adjustment.PageSize = 100000D;
		this.spinBpred2levHistSize.ClimbRate = 1D;
		this.spinBpred2levHistSize.Numeric = true;
		this.spinBpred2levHistSize.Value = 8D;
		this.fixed1.Add(this.spinBpred2levHistSize);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpred2levHistSize]));
		w27.X = 302;
		w27.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBpredBimodTableSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinBpredBimodTableSize.CanFocus = true;
		this.spinBpredBimodTableSize.Name = "spinBpredBimodTableSize";
		this.spinBpredBimodTableSize.Adjustment.PageIncrement = 10D;
		this.spinBpredBimodTableSize.Adjustment.PageSize = 100000D;
		this.spinBpredBimodTableSize.ClimbRate = 1D;
		this.spinBpredBimodTableSize.Numeric = true;
		this.spinBpredBimodTableSize.Value = 512D;
		this.fixed1.Add(this.spinBpredBimodTableSize);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBpredBimodTableSize]));
		w28.X = 301;
		w28.Y = 270;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpred2levHistSize = new global::Gtk.Label();
		this.lbBpred2levHistSize.Name = "lbBpred2levHistSize";
		this.lbBpred2levHistSize.LabelProp = global::Mono.Unix.Catalog.GetString("History Size:");
		this.fixed1.Add(this.lbBpred2levHistSize);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpred2levHistSize]));
		w29.X = 223;
		w29.Y = 243;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredBimodTableSize = new global::Gtk.Label();
		this.lbBpredBimodTableSize.Name = "lbBpredBimodTableSize";
		this.lbBpredBimodTableSize.LabelProp = global::Mono.Unix.Catalog.GetString("Table Size:");
		this.fixed1.Add(this.lbBpredBimodTableSize);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredBimodTableSize]));
		w30.X = 234;
		w30.Y = 272;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredBtbAssociativity = new global::Gtk.Label();
		this.lbBpredBtbAssociativity.Name = "lbBpredBtbAssociativity";
		this.lbBpredBtbAssociativity.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbBpredBtbAssociativity);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredBtbAssociativity]));
		w31.X = 220;
		w31.Y = 335;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBpredSpecUpdate = new global::Gtk.Label();
		this.lbBpredSpecUpdate.Name = "lbBpredSpecUpdate";
		this.lbBpredSpecUpdate.LabelProp = global::Mono.Unix.Catalog.GetString("Spec Update:");
		this.fixed1.Add(this.lbBpredSpecUpdate);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBpredSpecUpdate]));
		w32.X = 228;
		w32.Y = 210;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboBpredSpecUpdate = global::Gtk.ComboBox.NewText();
		this.comboBpredSpecUpdate.AppendText(global::Mono.Unix.Catalog.GetString("null"));
		this.comboBpredSpecUpdate.AppendText(global::Mono.Unix.Catalog.GetString("ID"));
		this.comboBpredSpecUpdate.AppendText(global::Mono.Unix.Catalog.GetString("WB"));
		this.comboBpredSpecUpdate.Name = "comboBpredSpecUpdate";
		this.comboBpredSpecUpdate.Active = 0;
		this.fixed1.Add(this.comboBpredSpecUpdate);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboBpredSpecUpdate]));
		w33.X = 312;
		w33.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkDecode = new global::Gtk.CheckButton();
		this.chkDecode.CanFocus = true;
		this.chkDecode.Name = "chkDecode";
		this.chkDecode.Label = global::Mono.Unix.Catalog.GetString("with decode");
		this.chkDecode.DrawIndicator = true;
		this.chkDecode.UseUnderline = true;
		this.fixed1.Add(this.chkDecode);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkDecode]));
		w34.X = 223;
		w34.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinDecodeWidth = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinDecodeWidth.CanFocus = true;
		this.spinDecodeWidth.Name = "spinDecodeWidth";
		this.spinDecodeWidth.Adjustment.PageIncrement = 10D;
		this.spinDecodeWidth.Adjustment.PageSize = 100000D;
		this.spinDecodeWidth.ClimbRate = 1D;
		this.spinDecodeWidth.Numeric = true;
		this.spinDecodeWidth.Value = 4D;
		this.fixed1.Add(this.spinDecodeWidth);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinDecodeWidth]));
		w35.X = 266;
		w35.Y = 122;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbDecodeWidth = new global::Gtk.Label();
		this.lbDecodeWidth.Name = "lbDecodeWidth";
		this.lbDecodeWidth.LabelProp = global::Mono.Unix.Catalog.GetString("Width:");
		this.fixed1.Add(this.lbDecodeWidth);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbDecodeWidth]));
		w36.X = 223;
		w36.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinCommitWidth = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinCommitWidth.CanFocus = true;
		this.spinCommitWidth.Name = "spinCommitWidth";
		this.spinCommitWidth.Adjustment.PageIncrement = 10D;
		this.spinCommitWidth.Adjustment.PageSize = 100000D;
		this.spinCommitWidth.ClimbRate = 1D;
		this.spinCommitWidth.Numeric = true;
		this.spinCommitWidth.Value = 4D;
		this.fixed1.Add(this.spinCommitWidth);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinCommitWidth]));
		w37.X = 315;
		w37.Y = 173;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkCommit = new global::Gtk.CheckButton();
		this.chkCommit.CanFocus = true;
		this.chkCommit.Name = "chkCommit";
		this.chkCommit.Label = global::Mono.Unix.Catalog.GetString("with Commit");
		this.chkCommit.DrawIndicator = true;
		this.chkCommit.UseUnderline = true;
		this.fixed1.Add(this.chkCommit);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkCommit]));
		w38.X = 217;
		w38.Y = 154;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkIssue = new global::Gtk.CheckButton();
		this.chkIssue.CanFocus = true;
		this.chkIssue.Name = "chkIssue";
		this.chkIssue.Label = global::Mono.Unix.Catalog.GetString("with isssue");
		this.chkIssue.DrawIndicator = true;
		this.chkIssue.UseUnderline = true;
		this.fixed1.Add(this.chkIssue);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkIssue]));
		w39.X = 14;
		w39.Y = 371;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbIssue = new global::Gtk.Label();
		this.lbIssue.Name = "lbIssue";
		this.lbIssue.LabelProp = global::Mono.Unix.Catalog.GetString("Issue option:");
		this.fixed1.Add(this.lbIssue);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbIssue]));
		w40.X = 117;
		w40.Y = 372;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboIssue = global::Gtk.ComboBox.NewText();
		this.comboIssue.AppendText(global::Mono.Unix.Catalog.GetString("width"));
		this.comboIssue.AppendText(global::Mono.Unix.Catalog.GetString("inorder"));
		this.comboIssue.AppendText(global::Mono.Unix.Catalog.GetString("wrongpath"));
		this.comboIssue.Name = "comboIssue";
		this.comboIssue.Active = 0;
		this.fixed1.Add(this.comboIssue);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboIssue]));
		w41.X = 199;
		w41.Y = 365;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbIssueWidth = new global::Gtk.Label();
		this.lbIssueWidth.Name = "lbIssueWidth";
		this.lbIssueWidth.LabelProp = global::Mono.Unix.Catalog.GetString("Issue Width:");
		this.fixed1.Add(this.lbIssueWidth);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbIssueWidth]));
		w42.X = 17;
		w42.Y = 403;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinIssueWidth = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinIssueWidth.CanFocus = true;
		this.spinIssueWidth.Name = "spinIssueWidth";
		this.spinIssueWidth.Adjustment.PageIncrement = 10D;
		this.spinIssueWidth.Adjustment.PageSize = 100000D;
		this.spinIssueWidth.ClimbRate = 1D;
		this.spinIssueWidth.Numeric = true;
		this.spinIssueWidth.Value = 4D;
		this.fixed1.Add(this.spinIssueWidth);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinIssueWidth]));
		w43.X = 98;
		w43.Y = 399;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboIssueInorder = global::Gtk.ComboBox.NewText();
		this.comboIssueInorder.AppendText(global::Mono.Unix.Catalog.GetString("false"));
		this.comboIssueInorder.AppendText(global::Mono.Unix.Catalog.GetString("true"));
		this.comboIssueInorder.Name = "comboIssueInorder";
		this.comboIssueInorder.Active = 0;
		this.fixed1.Add(this.comboIssueInorder);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboIssueInorder]));
		w44.X = 101;
		w44.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbIssueInorder = new global::Gtk.Label();
		this.lbIssueInorder.Name = "lbIssueInorder";
		this.lbIssueInorder.LabelProp = global::Mono.Unix.Catalog.GetString("Issue Inorder:");
		this.fixed1.Add(this.lbIssueInorder);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbIssueInorder]));
		w45.X = 13;
		w45.Y = 438;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbCommitWidth = new global::Gtk.Label();
		this.lbCommitWidth.Name = "lbCommitWidth";
		this.lbCommitWidth.LabelProp = global::Mono.Unix.Catalog.GetString("Commit Width:");
		this.fixed1.Add(this.lbCommitWidth);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbCommitWidth]));
		w46.X = 219;
		w46.Y = 180;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbIssueWrongPath = new global::Gtk.Label();
		this.lbIssueWrongPath.Name = "lbIssueWrongPath";
		this.lbIssueWrongPath.LabelProp = global::Mono.Unix.Catalog.GetString("Wrong Path:");
		this.fixed1.Add(this.lbIssueWrongPath);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbIssueWrongPath]));
		w47.X = 176;
		w47.Y = 440;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboIssueWrongPath = global::Gtk.ComboBox.NewText();
		this.comboIssueWrongPath.AppendText(global::Mono.Unix.Catalog.GetString("true"));
		this.comboIssueWrongPath.AppendText(global::Mono.Unix.Catalog.GetString("false"));
		this.comboIssueWrongPath.Name = "comboIssueWrongPath";
		this.comboIssueWrongPath.Active = 0;
		this.fixed1.Add(this.comboIssueWrongPath);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboIssueWrongPath]));
		w48.X = 253;
		w48.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkRuu = new global::Gtk.CheckButton();
		this.chkRuu.CanFocus = true;
		this.chkRuu.Name = "chkRuu";
		this.chkRuu.Label = global::Mono.Unix.Catalog.GetString("with ruu");
		this.chkRuu.DrawIndicator = true;
		this.chkRuu.UseUnderline = true;
		this.fixed1.Add(this.chkRuu);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkRuu]));
		w49.X = 12;
		w49.Y = 479;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinRuuSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinRuuSize.CanFocus = true;
		this.spinRuuSize.Name = "spinRuuSize";
		this.spinRuuSize.Adjustment.PageIncrement = 10D;
		this.spinRuuSize.Adjustment.PageSize = 100000D;
		this.spinRuuSize.ClimbRate = 1D;
		this.spinRuuSize.Numeric = true;
		this.spinRuuSize.Value = 16D;
		this.fixed1.Add(this.spinRuuSize);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinRuuSize]));
		w50.X = 159;
		w50.Y = 476;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkLsq = new global::Gtk.CheckButton();
		this.chkLsq.CanFocus = true;
		this.chkLsq.Name = "chkLsq";
		this.chkLsq.Label = global::Mono.Unix.Catalog.GetString("with lsq");
		this.chkLsq.DrawIndicator = true;
		this.chkLsq.UseUnderline = true;
		this.fixed1.Add(this.chkLsq);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkLsq]));
		w51.X = 12;
		w51.Y = 509;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbRuuSize = new global::Gtk.Label();
		this.lbRuuSize.Name = "lbRuuSize";
		this.lbRuuSize.LabelProp = global::Mono.Unix.Catalog.GetString("Ruu Size:");
		this.fixed1.Add(this.lbRuuSize);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbRuuSize]));
		w52.X = 94;
		w52.Y = 480;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLsqSize = new global::Gtk.SpinButton(0D, 9000000000D, 1D);
		this.spinLsqSize.CanFocus = true;
		this.spinLsqSize.Name = "spinLsqSize";
		this.spinLsqSize.Adjustment.PageIncrement = 10D;
		this.spinLsqSize.Adjustment.PageSize = 100000D;
		this.spinLsqSize.ClimbRate = 1D;
		this.spinLsqSize.Numeric = true;
		this.spinLsqSize.Value = 8D;
		this.fixed1.Add(this.spinLsqSize);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLsqSize]));
		w53.X = 159;
		w53.Y = 508;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLsqSize = new global::Gtk.Label();
		this.lbLsqSize.Name = "lbLsqSize";
		this.lbLsqSize.LabelProp = global::Mono.Unix.Catalog.GetString("Lsq Size:");
		this.fixed1.Add(this.lbLsqSize);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLsqSize]));
		w54.X = 100;
		w54.Y = 511;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkDL1 = new global::Gtk.CheckButton();
		this.chkDL1.CanFocus = true;
		this.chkDL1.Name = "chkDL1";
		this.chkDL1.Label = global::Mono.Unix.Catalog.GetString("with Data Cache L1");
		this.chkDL1.Active = true;
		this.chkDL1.DrawIndicator = true;
		this.chkDL1.UseUnderline = true;
		this.fixed1.Add(this.chkDL1);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkDL1]));
		w55.X = 453;
		w55.Y = 47;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsDL1 = new global::Gtk.Label();
		this.lbNumSetsDL1.Name = "lbNumSetsDL1";
		this.lbNumSetsDL1.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsDL1);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsDL1]));
		w56.X = 454;
		w56.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsDL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsDL1.CanFocus = true;
		this.spinNumSetsDL1.Name = "spinNumSetsDL1";
		this.spinNumSetsDL1.Adjustment.PageIncrement = 10D;
		this.spinNumSetsDL1.Adjustment.PageSize = 100000D;
		this.spinNumSetsDL1.ClimbRate = 1D;
		this.spinNumSetsDL1.Numeric = true;
		this.spinNumSetsDL1.Value = 128D;
		this.fixed1.Add(this.spinNumSetsDL1);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsDL1]));
		w57.X = 553;
		w57.Y = 71;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeDL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeDL1.CanFocus = true;
		this.spinBlockSizeDL1.Name = "spinBlockSizeDL1";
		this.spinBlockSizeDL1.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeDL1.Adjustment.PageSize = 100000D;
		this.spinBlockSizeDL1.ClimbRate = 1D;
		this.spinBlockSizeDL1.Numeric = true;
		this.spinBlockSizeDL1.Value = 32D;
		this.fixed1.Add(this.spinBlockSizeDL1);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeDL1]));
		w58.X = 553;
		w58.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityDL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityDL1.CanFocus = true;
		this.spinAssociativityDL1.Name = "spinAssociativityDL1";
		this.spinAssociativityDL1.Adjustment.PageIncrement = 10D;
		this.spinAssociativityDL1.Adjustment.PageSize = 100000D;
		this.spinAssociativityDL1.ClimbRate = 1D;
		this.spinAssociativityDL1.Numeric = true;
		this.spinAssociativityDL1.Value = 4D;
		this.fixed1.Add(this.spinAssociativityDL1);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityDL1]));
		w59.X = 552;
		w59.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementDL1 = global::Gtk.ComboBox.NewText();
		this.comboReplacementDL1.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementDL1.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementDL1.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementDL1.Name = "comboReplacementDL1";
		this.comboReplacementDL1.Active = 0;
		this.fixed1.Add(this.comboReplacementDL1);
		global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementDL1]));
		w60.X = 537;
		w60.Y = 168;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkDL2 = new global::Gtk.CheckButton();
		this.chkDL2.CanFocus = true;
		this.chkDL2.Name = "chkDL2";
		this.chkDL2.Label = global::Mono.Unix.Catalog.GetString("with Data Cache L2");
		this.chkDL2.Active = true;
		this.chkDL2.DrawIndicator = true;
		this.chkDL2.UseUnderline = true;
		this.fixed1.Add(this.chkDL2);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkDL2]));
		w61.X = 616;
		w61.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityDL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityDL2.CanFocus = true;
		this.spinAssociativityDL2.Name = "spinAssociativityDL2";
		this.spinAssociativityDL2.Adjustment.PageIncrement = 10D;
		this.spinAssociativityDL2.Adjustment.PageSize = 100000D;
		this.spinAssociativityDL2.ClimbRate = 1D;
		this.spinAssociativityDL2.Numeric = true;
		this.spinAssociativityDL2.Value = 4D;
		this.fixed1.Add(this.spinAssociativityDL2);
		global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityDL2]));
		w62.X = 724;
		w62.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLatDL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinLatDL2.CanFocus = true;
		this.spinLatDL2.Name = "spinLatDL2";
		this.spinLatDL2.Adjustment.PageIncrement = 10D;
		this.spinLatDL2.Adjustment.PageSize = 100000D;
		this.spinLatDL2.ClimbRate = 1D;
		this.spinLatDL2.Numeric = true;
		this.spinLatDL2.Value = 6D;
		this.fixed1.Add(this.spinLatDL2);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLatDL2]));
		w63.X = 723;
		w63.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeDL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeDL2.CanFocus = true;
		this.spinBlockSizeDL2.Name = "spinBlockSizeDL2";
		this.spinBlockSizeDL2.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeDL2.Adjustment.PageSize = 100000D;
		this.spinBlockSizeDL2.ClimbRate = 1D;
		this.spinBlockSizeDL2.Numeric = true;
		this.spinBlockSizeDL2.Value = 64D;
		this.fixed1.Add(this.spinBlockSizeDL2);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeDL2]));
		w64.X = 725;
		w64.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsDL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsDL2.CanFocus = true;
		this.spinNumSetsDL2.Name = "spinNumSetsDL2";
		this.spinNumSetsDL2.Adjustment.PageIncrement = 10D;
		this.spinNumSetsDL2.Adjustment.PageSize = 100000D;
		this.spinNumSetsDL2.ClimbRate = 1D;
		this.spinNumSetsDL2.Numeric = true;
		this.spinNumSetsDL2.Value = 1024D;
		this.fixed1.Add(this.spinNumSetsDL2);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsDL2]));
		w65.X = 725;
		w65.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementDL2 = global::Gtk.ComboBox.NewText();
		this.comboReplacementDL2.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementDL2.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementDL2.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementDL2.Name = "comboReplacementDL2";
		this.comboReplacementDL2.Active = 0;
		this.fixed1.Add(this.comboReplacementDL2);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementDL2]));
		w66.X = 707;
		w66.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLatDL2 = new global::Gtk.Label();
		this.lbLatDL2.Name = "lbLatDL2";
		this.lbLatDL2.LabelProp = global::Mono.Unix.Catalog.GetString("Latency:");
		this.fixed1.Add(this.lbLatDL2);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLatDL2]));
		w67.X = 662;
		w67.Y = 205;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementDL2 = new global::Gtk.Label();
		this.lbReplacementDL2.Name = "lbReplacementDL2";
		this.lbReplacementDL2.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementDL2);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementDL2]));
		w68.X = 622;
		w68.Y = 174;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityDL2 = new global::Gtk.Label();
		this.lbAssociativityDL2.Name = "lbAssociativityDL2";
		this.lbAssociativityDL2.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityDL2);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityDL2]));
		w69.X = 639;
		w69.Y = 138;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeDL2 = new global::Gtk.Label();
		this.lbBlockSizeDL2.Name = "lbBlockSizeDL2";
		this.lbBlockSizeDL2.LabelProp = global::Mono.Unix.Catalog.GetString("Block Size:");
		this.fixed1.Add(this.lbBlockSizeDL2);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeDL2]));
		w70.X = 656;
		w70.Y = 105;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsDL2 = new global::Gtk.Label();
		this.lbNumSetsDL2.Name = "lbNumSetsDL2";
		this.lbNumSetsDL2.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsDL2);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsDL2]));
		w71.X = 620;
		w71.Y = 77;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLatDL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinLatDL1.CanFocus = true;
		this.spinLatDL1.Name = "spinLatDL1";
		this.spinLatDL1.Adjustment.PageIncrement = 10D;
		this.spinLatDL1.Adjustment.PageSize = 100000D;
		this.spinLatDL1.ClimbRate = 1D;
		this.spinLatDL1.Numeric = true;
		this.spinLatDL1.Value = 1D;
		this.fixed1.Add(this.spinLatDL1);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLatDL1]));
		w72.X = 555;
		w72.Y = 206;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLatDL1 = new global::Gtk.Label();
		this.lbLatDL1.Name = "lbLatDL1";
		this.lbLatDL1.LabelProp = global::Mono.Unix.Catalog.GetString("Latency:");
		this.fixed1.Add(this.lbLatDL1);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLatDL1]));
		w73.X = 497;
		w73.Y = 208;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementDL1 = new global::Gtk.Label();
		this.lbReplacementDL1.Name = "lbReplacementDL1";
		this.lbReplacementDL1.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementDL1);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementDL1]));
		w74.X = 454;
		w74.Y = 173;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityDL1 = new global::Gtk.Label();
		this.lbAssociativityDL1.Name = "lbAssociativityDL1";
		this.lbAssociativityDL1.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityDL1);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityDL1]));
		w75.X = 469;
		w75.Y = 139;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeDL1 = new global::Gtk.Label();
		this.lbBlockSizeDL1.Name = "lbBlockSizeDL1";
		this.lbBlockSizeDL1.LabelProp = global::Mono.Unix.Catalog.GetString("Block Size:");
		this.fixed1.Add(this.lbBlockSizeDL1);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeDL1]));
		w76.X = 488;
		w76.Y = 108;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkIL1 = new global::Gtk.CheckButton();
		this.chkIL1.CanFocus = true;
		this.chkIL1.Name = "chkIL1";
		this.chkIL1.Label = global::Mono.Unix.Catalog.GetString("with Instruction Cache L1");
		this.chkIL1.Active = true;
		this.chkIL1.DrawIndicator = true;
		this.chkIL1.UseUnderline = true;
		this.fixed1.Add(this.chkIL1);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkIL1]));
		w77.X = 435;
		w77.Y = 241;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsIL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsIL1.CanFocus = true;
		this.spinNumSetsIL1.Name = "spinNumSetsIL1";
		this.spinNumSetsIL1.Adjustment.PageIncrement = 10D;
		this.spinNumSetsIL1.Adjustment.PageSize = 100000D;
		this.spinNumSetsIL1.ClimbRate = 1D;
		this.spinNumSetsIL1.Numeric = true;
		this.spinNumSetsIL1.Value = 512D;
		this.fixed1.Add(this.spinNumSetsIL1);
		global::Gtk.Fixed.FixedChild w78 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsIL1]));
		w78.X = 552;
		w78.Y = 265;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeIL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeIL1.CanFocus = true;
		this.spinBlockSizeIL1.Name = "spinBlockSizeIL1";
		this.spinBlockSizeIL1.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeIL1.Adjustment.PageSize = 100000D;
		this.spinBlockSizeIL1.ClimbRate = 1D;
		this.spinBlockSizeIL1.Numeric = true;
		this.spinBlockSizeIL1.Value = 32D;
		this.fixed1.Add(this.spinBlockSizeIL1);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeIL1]));
		w79.X = 551;
		w79.Y = 297;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityIL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityIL1.CanFocus = true;
		this.spinAssociativityIL1.Name = "spinAssociativityIL1";
		this.spinAssociativityIL1.Adjustment.PageIncrement = 10D;
		this.spinAssociativityIL1.Adjustment.PageSize = 100000D;
		this.spinAssociativityIL1.ClimbRate = 1D;
		this.spinAssociativityIL1.Numeric = true;
		this.spinAssociativityIL1.Value = 1D;
		this.fixed1.Add(this.spinAssociativityIL1);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityIL1]));
		w80.X = 550;
		w80.Y = 330;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementIL1 = global::Gtk.ComboBox.NewText();
		this.comboReplacementIL1.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementIL1.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementIL1.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementIL1.Name = "comboReplacementIL1";
		this.comboReplacementIL1.Active = 0;
		this.fixed1.Add(this.comboReplacementIL1);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementIL1]));
		w81.X = 534;
		w81.Y = 361;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLatIL1 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinLatIL1.CanFocus = true;
		this.spinLatIL1.Name = "spinLatIL1";
		this.spinLatIL1.Adjustment.PageIncrement = 10D;
		this.spinLatIL1.Adjustment.PageSize = 100000D;
		this.spinLatIL1.ClimbRate = 1D;
		this.spinLatIL1.Numeric = true;
		this.spinLatIL1.Value = 1D;
		this.fixed1.Add(this.spinLatIL1);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLatIL1]));
		w82.X = 549;
		w82.Y = 402;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsIL1 = new global::Gtk.Label();
		this.lbNumSetsIL1.Name = "lbNumSetsIL1";
		this.lbNumSetsIL1.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsIL1);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsIL1]));
		w83.X = 449;
		w83.Y = 267;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeIL1 = new global::Gtk.Label();
		this.lbBlockSizeIL1.Name = "lbBlockSizeIL1";
		this.lbBlockSizeIL1.LabelProp = global::Mono.Unix.Catalog.GetString("Block Size:");
		this.fixed1.Add(this.lbBlockSizeIL1);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeIL1]));
		w84.X = 483;
		w84.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityIL1 = new global::Gtk.Label();
		this.lbAssociativityIL1.Name = "lbAssociativityIL1";
		this.lbAssociativityIL1.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityIL1);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityIL1]));
		w85.X = 467;
		w85.Y = 334;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementIL1 = new global::Gtk.Label();
		this.lbReplacementIL1.Name = "lbReplacementIL1";
		this.lbReplacementIL1.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementIL1);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementIL1]));
		w86.X = 446;
		w86.Y = 368;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLatIL1 = new global::Gtk.Label();
		this.lbLatIL1.Name = "lbLatIL1";
		this.lbLatIL1.LabelProp = global::Mono.Unix.Catalog.GetString("Latency:");
		this.fixed1.Add(this.lbLatIL1);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLatIL1]));
		w87.X = 492;
		w87.Y = 404;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkUnifiedIL1 = new global::Gtk.CheckButton();
		this.chkUnifiedIL1.CanFocus = true;
		this.chkUnifiedIL1.Name = "chkUnifiedIL1";
		this.chkUnifiedIL1.Label = global::Mono.Unix.Catalog.GetString("Unified Cache");
		this.chkUnifiedIL1.DrawIndicator = true;
		this.chkUnifiedIL1.UseUnderline = true;
		this.fixed1.Add(this.chkUnifiedIL1);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkUnifiedIL1]));
		w88.X = 495;
		w88.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkIL2 = new global::Gtk.CheckButton();
		this.chkIL2.CanFocus = true;
		this.chkIL2.Name = "chkIL2";
		this.chkIL2.Label = global::Mono.Unix.Catalog.GetString("with Instruction Cache L2");
		this.chkIL2.Active = true;
		this.chkIL2.DrawIndicator = true;
		this.chkIL2.UseUnderline = true;
		this.fixed1.Add(this.chkIL2);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkIL2]));
		w89.X = 627;
		w89.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsIL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsIL2.CanFocus = true;
		this.spinNumSetsIL2.Name = "spinNumSetsIL2";
		this.spinNumSetsIL2.Adjustment.PageIncrement = 10D;
		this.spinNumSetsIL2.Adjustment.PageSize = 100000D;
		this.spinNumSetsIL2.ClimbRate = 1D;
		this.spinNumSetsIL2.Numeric = true;
		this.spinNumSetsIL2.Value = 1024D;
		this.fixed1.Add(this.spinNumSetsIL2);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsIL2]));
		w90.X = 746;
		w90.Y = 262;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeIL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeIL2.CanFocus = true;
		this.spinBlockSizeIL2.Name = "spinBlockSizeIL2";
		this.spinBlockSizeIL2.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeIL2.Adjustment.PageSize = 100000D;
		this.spinBlockSizeIL2.ClimbRate = 1D;
		this.spinBlockSizeIL2.Numeric = true;
		this.spinBlockSizeIL2.Value = 64D;
		this.fixed1.Add(this.spinBlockSizeIL2);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeIL2]));
		w91.X = 746;
		w91.Y = 294;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityIL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityIL2.CanFocus = true;
		this.spinAssociativityIL2.Name = "spinAssociativityIL2";
		this.spinAssociativityIL2.Adjustment.PageIncrement = 10D;
		this.spinAssociativityIL2.Adjustment.PageSize = 100000D;
		this.spinAssociativityIL2.ClimbRate = 1D;
		this.spinAssociativityIL2.Numeric = true;
		this.spinAssociativityIL2.Value = 4D;
		this.fixed1.Add(this.spinAssociativityIL2);
		global::Gtk.Fixed.FixedChild w92 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityIL2]));
		w92.X = 746;
		w92.Y = 326;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementIL2 = global::Gtk.ComboBox.NewText();
		this.comboReplacementIL2.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementIL2.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementIL2.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementIL2.Name = "comboReplacementIL2";
		this.comboReplacementIL2.Active = 0;
		this.fixed1.Add(this.comboReplacementIL2);
		global::Gtk.Fixed.FixedChild w93 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementIL2]));
		w93.X = 730;
		w93.Y = 358;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLatIL2 = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinLatIL2.CanFocus = true;
		this.spinLatIL2.Name = "spinLatIL2";
		this.spinLatIL2.Adjustment.PageIncrement = 10D;
		this.spinLatIL2.Adjustment.PageSize = 100000D;
		this.spinLatIL2.ClimbRate = 1D;
		this.spinLatIL2.Numeric = true;
		this.spinLatIL2.Value = 6D;
		this.fixed1.Add(this.spinLatIL2);
		global::Gtk.Fixed.FixedChild w94 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLatIL2]));
		w94.X = 746;
		w94.Y = 396;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkUnifiedIL2 = new global::Gtk.CheckButton();
		this.chkUnifiedIL2.CanFocus = true;
		this.chkUnifiedIL2.Name = "chkUnifiedIL2";
		this.chkUnifiedIL2.Label = global::Mono.Unix.Catalog.GetString("Unified Cache");
		this.chkUnifiedIL2.DrawIndicator = true;
		this.chkUnifiedIL2.UseUnderline = true;
		this.fixed1.Add(this.chkUnifiedIL2);
		global::Gtk.Fixed.FixedChild w95 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkUnifiedIL2]));
		w95.X = 692;
		w95.Y = 427;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsIL2 = new global::Gtk.Label();
		this.lbNumSetsIL2.Name = "lbNumSetsIL2";
		this.lbNumSetsIL2.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsIL2);
		global::Gtk.Fixed.FixedChild w96 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsIL2]));
		w96.X = 644;
		w96.Y = 266;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeIL2 = new global::Gtk.Label();
		this.lbBlockSizeIL2.Name = "lbBlockSizeIL2";
		this.lbBlockSizeIL2.LabelProp = global::Mono.Unix.Catalog.GetString("BlockSize:");
		this.fixed1.Add(this.lbBlockSizeIL2);
		global::Gtk.Fixed.FixedChild w97 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeIL2]));
		w97.X = 681;
		w97.Y = 297;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityIL2 = new global::Gtk.Label();
		this.lbAssociativityIL2.Name = "lbAssociativityIL2";
		this.lbAssociativityIL2.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityIL2);
		global::Gtk.Fixed.FixedChild w98 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityIL2]));
		w98.X = 659;
		w98.Y = 328;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementIL2 = new global::Gtk.Label();
		this.lbReplacementIL2.Name = "lbReplacementIL2";
		this.lbReplacementIL2.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementIL2);
		global::Gtk.Fixed.FixedChild w99 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementIL2]));
		w99.X = 643;
		w99.Y = 363;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLatIL2 = new global::Gtk.Label();
		this.lbLatIL2.Name = "lbLatIL2";
		this.lbLatIL2.LabelProp = global::Mono.Unix.Catalog.GetString("Latency:");
		this.fixed1.Add(this.lbLatIL2);
		global::Gtk.Fixed.FixedChild w100 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLatIL2]));
		w100.X = 686;
		w100.Y = 397;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsDTLB = new global::Gtk.Label();
		this.lbNumSetsDTLB.Name = "lbNumSetsDTLB";
		this.lbNumSetsDTLB.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsDTLB);
		global::Gtk.Fixed.FixedChild w101 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsDTLB]));
		w101.X = 790;
		w101.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkDTLB = new global::Gtk.CheckButton();
		this.chkDTLB.CanFocus = true;
		this.chkDTLB.Name = "chkDTLB";
		this.chkDTLB.Label = global::Mono.Unix.Catalog.GetString("with TLB Data");
		this.chkDTLB.Active = true;
		this.chkDTLB.DrawIndicator = true;
		this.chkDTLB.UseUnderline = true;
		this.fixed1.Add(this.chkDTLB);
		global::Gtk.Fixed.FixedChild w102 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkDTLB]));
		w102.X = 823;
		w102.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsDTLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsDTLB.CanFocus = true;
		this.spinNumSetsDTLB.Name = "spinNumSetsDTLB";
		this.spinNumSetsDTLB.Adjustment.PageIncrement = 10D;
		this.spinNumSetsDTLB.Adjustment.PageSize = 100000D;
		this.spinNumSetsDTLB.ClimbRate = 1D;
		this.spinNumSetsDTLB.Numeric = true;
		this.spinNumSetsDTLB.Value = 32D;
		this.fixed1.Add(this.spinNumSetsDTLB);
		global::Gtk.Fixed.FixedChild w103 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsDTLB]));
		w103.X = 888;
		w103.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeDTLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeDTLB.CanFocus = true;
		this.spinBlockSizeDTLB.Name = "spinBlockSizeDTLB";
		this.spinBlockSizeDTLB.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeDTLB.Adjustment.PageSize = 100000D;
		this.spinBlockSizeDTLB.ClimbRate = 1D;
		this.spinBlockSizeDTLB.Numeric = true;
		this.spinBlockSizeDTLB.Value = 4096D;
		this.fixed1.Add(this.spinBlockSizeDTLB);
		global::Gtk.Fixed.FixedChild w104 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeDTLB]));
		w104.X = 886;
		w104.Y = 103;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeDTLB = new global::Gtk.Label();
		this.lbBlockSizeDTLB.Name = "lbBlockSizeDTLB";
		this.lbBlockSizeDTLB.LabelProp = global::Mono.Unix.Catalog.GetString("Block Size:");
		this.fixed1.Add(this.lbBlockSizeDTLB);
		global::Gtk.Fixed.FixedChild w105 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeDTLB]));
		w105.X = 819;
		w105.Y = 106;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityDTLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityDTLB.CanFocus = true;
		this.spinAssociativityDTLB.Name = "spinAssociativityDTLB";
		this.spinAssociativityDTLB.Adjustment.PageIncrement = 10D;
		this.spinAssociativityDTLB.Adjustment.PageSize = 100000D;
		this.spinAssociativityDTLB.ClimbRate = 1D;
		this.spinAssociativityDTLB.Numeric = true;
		this.spinAssociativityDTLB.Value = 4D;
		this.fixed1.Add(this.spinAssociativityDTLB);
		global::Gtk.Fixed.FixedChild w106 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityDTLB]));
		w106.X = 884;
		w106.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityDTLB = new global::Gtk.Label();
		this.lbAssociativityDTLB.Name = "lbAssociativityDTLB";
		this.lbAssociativityDTLB.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityDTLB);
		global::Gtk.Fixed.FixedChild w107 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityDTLB]));
		w107.X = 798;
		w107.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementDTLB = global::Gtk.ComboBox.NewText();
		this.comboReplacementDTLB.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementDTLB.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementDTLB.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementDTLB.Name = "comboReplacementDTLB";
		this.comboReplacementDTLB.Active = 0;
		this.fixed1.Add(this.comboReplacementDTLB);
		global::Gtk.Fixed.FixedChild w108 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementDTLB]));
		w108.X = 868;
		w108.Y = 165;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementDTLB = new global::Gtk.Label();
		this.lbReplacementDTLB.Name = "lbReplacementDTLB";
		this.lbReplacementDTLB.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementDTLB);
		global::Gtk.Fixed.FixedChild w109 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementDTLB]));
		w109.X = 785;
		w109.Y = 172;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbLatTLB = new global::Gtk.Label();
		this.lbLatTLB.Name = "lbLatTLB";
		this.lbLatTLB.LabelProp = global::Mono.Unix.Catalog.GetString("TLB Latency:");
		this.fixed1.Add(this.lbLatTLB);
		global::Gtk.Fixed.FixedChild w110 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbLatTLB]));
		w110.X = 792;
		w110.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinLatTLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinLatTLB.CanFocus = true;
		this.spinLatTLB.Name = "spinLatTLB";
		this.spinLatTLB.Adjustment.PageIncrement = 10D;
		this.spinLatTLB.Adjustment.PageSize = 100000D;
		this.spinLatTLB.ClimbRate = 1D;
		this.spinLatTLB.Numeric = true;
		this.spinLatTLB.Value = 30D;
		this.fixed1.Add(this.spinLatTLB);
		global::Gtk.Fixed.FixedChild w111 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinLatTLB]));
		w111.X = 882;
		w111.Y = 201;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkITLB = new global::Gtk.CheckButton();
		this.chkITLB.CanFocus = true;
		this.chkITLB.Name = "chkITLB";
		this.chkITLB.Label = global::Mono.Unix.Catalog.GetString("with TLB Instruction");
		this.chkITLB.Active = true;
		this.chkITLB.DrawIndicator = true;
		this.chkITLB.UseUnderline = true;
		this.fixed1.Add(this.chkITLB);
		global::Gtk.Fixed.FixedChild w112 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkITLB]));
		w112.X = 816;
		w112.Y = 240;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbNumSetsITLB = new global::Gtk.Label();
		this.lbNumSetsITLB.Name = "lbNumSetsITLB";
		this.lbNumSetsITLB.LabelProp = global::Mono.Unix.Catalog.GetString("Number of Sets:");
		this.fixed1.Add(this.lbNumSetsITLB);
		global::Gtk.Fixed.FixedChild w113 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbNumSetsITLB]));
		w113.X = 812;
		w113.Y = 266;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinNumSetsITLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinNumSetsITLB.CanFocus = true;
		this.spinNumSetsITLB.Name = "spinNumSetsITLB";
		this.spinNumSetsITLB.Adjustment.PageIncrement = 10D;
		this.spinNumSetsITLB.Adjustment.PageSize = 100000D;
		this.spinNumSetsITLB.ClimbRate = 1D;
		this.spinNumSetsITLB.Numeric = true;
		this.spinNumSetsITLB.Value = 16D;
		this.fixed1.Add(this.spinNumSetsITLB);
		global::Gtk.Fixed.FixedChild w114 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinNumSetsITLB]));
		w114.X = 910;
		w114.Y = 261;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinBlockSizeITLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinBlockSizeITLB.CanFocus = true;
		this.spinBlockSizeITLB.Name = "spinBlockSizeITLB";
		this.spinBlockSizeITLB.Adjustment.PageIncrement = 10D;
		this.spinBlockSizeITLB.Adjustment.PageSize = 100000D;
		this.spinBlockSizeITLB.ClimbRate = 1D;
		this.spinBlockSizeITLB.Numeric = true;
		this.spinBlockSizeITLB.Value = 4096D;
		this.fixed1.Add(this.spinBlockSizeITLB);
		global::Gtk.Fixed.FixedChild w115 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinBlockSizeITLB]));
		w115.X = 909;
		w115.Y = 292;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinAssociativityITLB = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinAssociativityITLB.CanFocus = true;
		this.spinAssociativityITLB.Name = "spinAssociativityITLB";
		this.spinAssociativityITLB.Adjustment.PageIncrement = 10D;
		this.spinAssociativityITLB.Adjustment.PageSize = 100000D;
		this.spinAssociativityITLB.ClimbRate = 1D;
		this.spinAssociativityITLB.Numeric = true;
		this.spinAssociativityITLB.Value = 4D;
		this.fixed1.Add(this.spinAssociativityITLB);
		global::Gtk.Fixed.FixedChild w116 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinAssociativityITLB]));
		w116.X = 908;
		w116.Y = 323;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboReplacementITLB = global::Gtk.ComboBox.NewText();
		this.comboReplacementITLB.AppendText(global::Mono.Unix.Catalog.GetString("LRU"));
		this.comboReplacementITLB.AppendText(global::Mono.Unix.Catalog.GetString("FIFO"));
		this.comboReplacementITLB.AppendText(global::Mono.Unix.Catalog.GetString("RAND"));
		this.comboReplacementITLB.Name = "comboReplacementITLB";
		this.comboReplacementITLB.Active = 0;
		this.fixed1.Add(this.comboReplacementITLB);
		global::Gtk.Fixed.FixedChild w117 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboReplacementITLB]));
		w117.X = 892;
		w117.Y = 354;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbBlockSizeITLB = new global::Gtk.Label();
		this.lbBlockSizeITLB.Name = "lbBlockSizeITLB";
		this.lbBlockSizeITLB.LabelProp = global::Mono.Unix.Catalog.GetString("Block Size:");
		this.fixed1.Add(this.lbBlockSizeITLB);
		global::Gtk.Fixed.FixedChild w118 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbBlockSizeITLB]));
		w118.X = 843;
		w118.Y = 295;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbAssociativityITLB = new global::Gtk.Label();
		this.lbAssociativityITLB.Name = "lbAssociativityITLB";
		this.lbAssociativityITLB.LabelProp = global::Mono.Unix.Catalog.GetString("Associativity:");
		this.fixed1.Add(this.lbAssociativityITLB);
		global::Gtk.Fixed.FixedChild w119 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbAssociativityITLB]));
		w119.X = 826;
		w119.Y = 326;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbReplacementITLB = new global::Gtk.Label();
		this.lbReplacementITLB.Name = "lbReplacementITLB";
		this.lbReplacementITLB.LabelProp = global::Mono.Unix.Catalog.GetString("Replacement:");
		this.fixed1.Add(this.lbReplacementITLB);
		global::Gtk.Fixed.FixedChild w120 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbReplacementITLB]));
		w120.X = 809;
		w120.Y = 360;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboCacheFlush = global::Gtk.ComboBox.NewText();
		this.comboCacheFlush.AppendText(global::Mono.Unix.Catalog.GetString("false"));
		this.comboCacheFlush.AppendText(global::Mono.Unix.Catalog.GetString("true"));
		this.comboCacheFlush.Name = "comboCacheFlush";
		this.comboCacheFlush.Active = 0;
		this.fixed1.Add(this.comboCacheFlush);
		global::Gtk.Fixed.FixedChild w121 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboCacheFlush]));
		w121.X = 549;
		w121.Y = 473;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboCacheIcompress = global::Gtk.ComboBox.NewText();
		this.comboCacheIcompress.AppendText(global::Mono.Unix.Catalog.GetString("false"));
		this.comboCacheIcompress.AppendText(global::Mono.Unix.Catalog.GetString("true"));
		this.comboCacheIcompress.Name = "comboCacheIcompress";
		this.comboCacheIcompress.Active = 0;
		this.fixed1.Add(this.comboCacheIcompress);
		global::Gtk.Fixed.FixedChild w122 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboCacheIcompress]));
		w122.X = 549;
		w122.Y = 516;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinMemWidth = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinMemWidth.CanFocus = true;
		this.spinMemWidth.Name = "spinMemWidth";
		this.spinMemWidth.Adjustment.PageIncrement = 10D;
		this.spinMemWidth.Adjustment.PageSize = 100000D;
		this.spinMemWidth.ClimbRate = 1D;
		this.spinMemWidth.Numeric = true;
		this.spinMemWidth.Value = 8D;
		this.fixed1.Add(this.spinMemWidth);
		global::Gtk.Fixed.FixedChild w123 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinMemWidth]));
		w123.X = 552;
		w123.Y = 564;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkCacheFlush = new global::Gtk.CheckButton();
		this.chkCacheFlush.CanFocus = true;
		this.chkCacheFlush.Name = "chkCacheFlush";
		this.chkCacheFlush.Label = global::Mono.Unix.Catalog.GetString("with cache:flush");
		this.chkCacheFlush.DrawIndicator = true;
		this.chkCacheFlush.UseUnderline = true;
		this.fixed1.Add(this.chkCacheFlush);
		global::Gtk.Fixed.FixedChild w124 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkCacheFlush]));
		w124.X = 426;
		w124.Y = 480;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkCacheIcompress = new global::Gtk.CheckButton();
		this.chkCacheIcompress.CanFocus = true;
		this.chkCacheIcompress.Name = "chkCacheIcompress";
		this.chkCacheIcompress.Label = global::Mono.Unix.Catalog.GetString("with cache:icompress");
		this.chkCacheIcompress.DrawIndicator = true;
		this.chkCacheIcompress.UseUnderline = true;
		this.fixed1.Add(this.chkCacheIcompress);
		global::Gtk.Fixed.FixedChild w125 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkCacheIcompress]));
		w125.X = 393;
		w125.Y = 521;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkMemWidth = new global::Gtk.CheckButton();
		this.chkMemWidth.CanFocus = true;
		this.chkMemWidth.Name = "chkMemWidth";
		this.chkMemWidth.Label = global::Mono.Unix.Catalog.GetString("with mem:width");
		this.chkMemWidth.DrawIndicator = true;
		this.chkMemWidth.UseUnderline = true;
		this.fixed1.Add(this.chkMemWidth);
		global::Gtk.Fixed.FixedChild w126 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkMemWidth]));
		w126.X = 425;
		w126.Y = 566;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkMemLat = new global::Gtk.CheckButton();
		this.chkMemLat.CanFocus = true;
		this.chkMemLat.Name = "chkMemLat";
		this.chkMemLat.Label = global::Mono.Unix.Catalog.GetString("with mem:lat");
		this.chkMemLat.DrawIndicator = true;
		this.chkMemLat.UseUnderline = true;
		this.fixed1.Add(this.chkMemLat);
		global::Gtk.Fixed.FixedChild w127 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkMemLat]));
		w127.X = 655;
		w127.Y = 478;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbMemLatInterChunk = new global::Gtk.Label();
		this.lbMemLatInterChunk.Name = "lbMemLatInterChunk";
		this.lbMemLatInterChunk.LabelProp = global::Mono.Unix.Catalog.GetString("Inter Chunk:");
		this.fixed1.Add(this.lbMemLatInterChunk);
		global::Gtk.Fixed.FixedChild w128 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbMemLatInterChunk]));
		w128.X = 664;
		w128.Y = 545;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbMemLatFirstChunk = new global::Gtk.Label();
		this.lbMemLatFirstChunk.Name = "lbMemLatFirstChunk";
		this.lbMemLatFirstChunk.LabelProp = global::Mono.Unix.Catalog.GetString("First Chunk:");
		this.fixed1.Add(this.lbMemLatFirstChunk);
		global::Gtk.Fixed.FixedChild w129 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbMemLatFirstChunk]));
		w129.X = 665;
		w129.Y = 510;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinMemLatInterChunk = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinMemLatInterChunk.CanFocus = true;
		this.spinMemLatInterChunk.Name = "spinMemLatInterChunk";
		this.spinMemLatInterChunk.Adjustment.PageIncrement = 10D;
		this.spinMemLatInterChunk.Adjustment.PageSize = 100000D;
		this.spinMemLatInterChunk.ClimbRate = 1D;
		this.spinMemLatInterChunk.Numeric = true;
		this.spinMemLatInterChunk.Value = 2D;
		this.fixed1.Add(this.spinMemLatInterChunk);
		global::Gtk.Fixed.FixedChild w130 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinMemLatInterChunk]));
		w130.X = 746;
		w130.Y = 540;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinMemLatFirstChunk = new global::Gtk.SpinButton(0D, 8192D, 1D);
		this.spinMemLatFirstChunk.CanFocus = true;
		this.spinMemLatFirstChunk.Name = "spinMemLatFirstChunk";
		this.spinMemLatFirstChunk.Adjustment.PageIncrement = 10D;
		this.spinMemLatFirstChunk.Adjustment.PageSize = 100000D;
		this.spinMemLatFirstChunk.ClimbRate = 1D;
		this.spinMemLatFirstChunk.Numeric = true;
		this.spinMemLatFirstChunk.Value = 18D;
		this.fixed1.Add(this.spinMemLatFirstChunk);
		global::Gtk.Fixed.FixedChild w131 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spinMemLatFirstChunk]));
		w131.X = 748;
		w131.Y = 506;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPopulate = new global::Gtk.Button();
		this.btnPopulate.CanFocus = true;
		this.btnPopulate.Name = "btnPopulate";
		this.btnPopulate.UseUnderline = true;
		this.btnPopulate.Label = global::Mono.Unix.Catalog.GetString("Populate");
		this.fixed1.Add(this.btnPopulate);
		global::Gtk.Fixed.FixedChild w132 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnPopulate]));
		w132.X = 375;
		w132.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSeeResults = new global::Gtk.Button();
		this.btnSeeResults.Sensitive = false;
		this.btnSeeResults.CanFocus = true;
		this.btnSeeResults.Name = "btnSeeResults";
		this.btnSeeResults.UseUnderline = true;
		this.btnSeeResults.Label = global::Mono.Unix.Catalog.GetString("See Results");
		this.fixed1.Add(this.btnSeeResults);
		global::Gtk.Fixed.FixedChild w133 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSeeResults]));
		w133.X = 312;
		w133.Y = 64;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 978;
		this.DefaultHeight = 630;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnStartServer.Clicked += new global::System.EventHandler(this.OnBtnStartServer);
		this.btnReset.Clicked += new global::System.EventHandler(this.OnBtnReset);
		this.btnHelp.Clicked += new global::System.EventHandler(this.OnBtnHelp);
		this.chkFetch.Toggled += new global::System.EventHandler(this.OnChkFetch);
		this.chkBpred.Toggled += new global::System.EventHandler(this.OnChkBpred);
		this.comboBpred.Changed += new global::System.EventHandler(this.OnComboBpred);
		this.chkDecode.Toggled += new global::System.EventHandler(this.OnChkDecode);
		this.chkCommit.Toggled += new global::System.EventHandler(this.OnChkCommit);
		this.chkIssue.Toggled += new global::System.EventHandler(this.OnChkIssue);
		this.comboIssue.Changed += new global::System.EventHandler(this.OnComboIssue);
		this.chkRuu.Toggled += new global::System.EventHandler(this.OnChkRuu);
		this.chkLsq.Toggled += new global::System.EventHandler(this.OnChkLsq);
		this.chkDL1.Toggled += new global::System.EventHandler(this.OnChkDL1);
		this.chkDL2.Toggled += new global::System.EventHandler(this.OnChkDL2);
		this.chkIL1.Toggled += new global::System.EventHandler(this.OnChkIL1);
		this.chkUnifiedIL1.Toggled += new global::System.EventHandler(this.OnUnifiedIL1);
		this.chkIL2.Toggled += new global::System.EventHandler(this.OnChkIL2);
		this.chkUnifiedIL2.Toggled += new global::System.EventHandler(this.OnUnifiedIL2);
		this.chkDTLB.Toggled += new global::System.EventHandler(this.OnChkDTLB);
		this.chkITLB.Toggled += new global::System.EventHandler(this.OnChkITLB);
		this.chkCacheFlush.Toggled += new global::System.EventHandler(this.OnChkCacheFlush);
		this.chkCacheIcompress.Toggled += new global::System.EventHandler(this.OnChkCacheIcompress);
		this.chkMemWidth.Toggled += new global::System.EventHandler(this.OnMemWidth);
		this.chkMemLat.Toggled += new global::System.EventHandler(this.OnMemLat);
		this.btnPopulate.Clicked += new global::System.EventHandler(this.OnBtnPopulate);
		this.btnSeeResults.Clicked += new global::System.EventHandler(this.OnBtnSeeResults);
	}
}
